name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate synthetic data
        run: python data/synthetic_generator.py
      - name: Smoke train
        run: python src/models/train.py
      - name: Smoke batch inference
        run: python src/inference/batch.py
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            out/**
            data/sample.csv
